// Importación de módulos y componentes de React y Material-UI
import Navbar from "./components/navbar";
import ResponsiveDrawer from "./components/sidebar";
import "../layout"; // Importación de estilos globales
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// Layout principal que envuelve toda la aplicación
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          {" "}
          {/* Inicio del diseño principal */}
          <ResponsiveDrawer /> {/* Barra lateral */}
          <div className="flex flex-col w-full">
            {" "}
            {/* Contenido principal */}
            <Navbar /> {/* Navbar */}
            <div className="w-full">{children}</div> {/* Contenido dinámico */}
          </div>
        </div>
      </body>
    </html>
  );
}

// Metadatos globales de la aplicación
export const metadata: Metadata = {
  title: "IntraNoc",
  description: "Generated by create next app",
};
